# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        

# Setup
title:            Stop Asian Hate Crime
tagline:          '#StopAsianHateCrime'
description:      'Tracking and reporting Asian hate crimes globally and provide insightful resources on how to stay safe during and after the pandemic.'
url:              
baseurl:          /

author:
  name:           'Ryan Han'
  url:            
paginate:         5

