# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        

# Setup
title:            Asian Care Fund
tagline:          '#StopAsianHateCrime'
description:      'Integrity, justice, and gratitude.'
url:              https://stopasianhate.github.io/
baseurl:          https://stopasianhate.github.io/

author:
  name:           'Ryan Han'
  url:            
paginate:         5

