# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        

# Setup
title:            Asian Care Fund
tagline:          '#StopAsianHateCrime'
description:      'Integrity, justice, and gratitude.'
url:              //asiancarefund.org
baseurl:          /

author:
  name:           'Ryan Han'
  url:            
paginate:         5

