# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        

# Setup
title:            Stop Asian Hate Crime
tagline:          'A Jekyll theme'
description:      'We condemn the horrific acts of hate and violence targeting the Asian American and Pacific Islander (AAPI) community, which culminated in the tragic mass shooting in Georgia on March 17th. We mourn the loss of life and grieve with the families that have been broken by this latest racist, misogynistic hate crime.'
url:              
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
