# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        

# Setup
title:            Asian Care Fund
tagline:          '#StopAsianHateCrime'
description:      'Integrity, justice, and gratitude.'
url:              https://asiancarefund.org/
baseurl:          https://asiancarefund.org/

author:
  name:           'Ryan Han'
  url:            
paginate:         5

